/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import reporte.ReporteJSON;
import tablaSimbolos.TablaClases;
import tablaSimbolos.TablaMetodos;
import tablaSimbolos.TablaVariables;
import json.SintaxJ;
import utils.LectorArchivos;

/**
 *
 * @author HP
 */
public class FrameAnalizador extends javax.swing.JFrame {

    private TablaClases tablaClases;
    private TablaVariables tablaVariables;
    private TablaMetodos tablaMetodos;
    private String rutaCarpeta1;
    private String rutaCarpeta2;

    /**
     * Creates new form FrameAnalizador
     */
    public FrameAnalizador() {
        initComponents();
        tablaClases = new TablaClases();
        tablaMetodos = new TablaMetodos();
        tablaVariables = new TablaVariables();
        rutaCarpeta1 = "";
        rutaCarpeta2 = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAnalizar = new javax.swing.JButton();
        botonReporteJson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteJSON = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        pathCarpeta1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonExaminarCarpeta1 = new javax.swing.JButton();
        pathCarpeta2 = new javax.swing.JTextField();
        botonExaminarCarpeta2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        botonAnalizar.setText("ANALIZAR");
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });

        botonReporteJson.setText("REPORTE JSON");
        botonReporteJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteJsonActionPerformed(evt);
            }
        });

        reporteJSON.setBackground(new java.awt.Color(51, 51, 51));
        reporteJSON.setColumns(20);
        reporteJSON.setForeground(new java.awt.Color(255, 255, 255));
        reporteJSON.setRows(5);
        jScrollPane1.setViewportView(reporteJSON);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISTA  DE  REPORTE  JSON");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CARPETA 1");

        botonExaminarCarpeta1.setText("CARGAR CARPETA");
        botonExaminarCarpeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExaminarCarpeta1ActionPerformed(evt);
            }
        });

        botonExaminarCarpeta2.setText("CARGAR CARPETA");
        botonExaminarCarpeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExaminarCarpeta2ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CARPETA 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(pathCarpeta1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonExaminarCarpeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(pathCarpeta2))
                                .addGap(28, 28, 28)
                                .addComponent(botonExaminarCarpeta2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonReporteJson, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                    .addComponent(botonAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathCarpeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonExaminarCarpeta1)
                    .addComponent(pathCarpeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonExaminarCarpeta2))
                .addGap(35, 35, 35)
                .addComponent(botonAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonReporteJson, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed

        /*
            ANALIZAMOS LAS CARPETAS CON SUS RESPECTIVOS ARCHIVOS.JAVA
         */
        for (int i = 0; i < 2; i++) {
            if (i == 0) {
                analizarCarpeta(rutaCarpeta1);
            } else if (i == 1) {
                analizarCarpeta(rutaCarpeta2);
            }
        }

        JOptionPane.showMessageDialog(null, "Analisis Exitoso");


    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void botonReporteJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteJsonActionPerformed

        ReporteJSON reporte = new ReporteJSON();

        reporte.agregarReporteClase(tablaClases.getClases());
        reporte.reporteVariables(tablaVariables.getVariables());
        reporte.generarReporteMetodos(tablaMetodos.getMetodos());

        reporte.generarReporteTotal();
        String reporteTotal = reporte.getReporteTotal();

        reporteJSON.setText(reporteTotal);
        LexerJson lexerJson = new LexerJson(new StringReader(reporteJSON.getText()));
        SintaxJ sintax = new SintaxJ(lexerJson);

        try {
            sintax.parse();
            JOptionPane.showMessageDialog(null, "Reporte Generado Correctamente");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_botonReporteJsonActionPerformed

    private void botonExaminarCarpeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExaminarCarpeta1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(this);
        pathCarpeta1.setText(fileChooser.getSelectedFile().getAbsolutePath());
        rutaCarpeta1 = pathCarpeta1.getText();


    }//GEN-LAST:event_botonExaminarCarpeta1ActionPerformed

    private void botonExaminarCarpeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExaminarCarpeta2ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(this);
        pathCarpeta2.setText(fileChooser.getSelectedFile().getAbsolutePath());
        rutaCarpeta2 = pathCarpeta2.getText();


    }//GEN-LAST:event_botonExaminarCarpeta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAnalizador().setVisible(true);
            }
        });
    }

    public void analizarCarpeta(String rutaCarpeta) {

        LectorArchivos lector = new LectorArchivos(rutaCarpeta);
        lector.run();

        for (int j = 0; j < lector.getArchivosJava().size(); j++) {
            String textoJava = lector.getArchivosJava().get(j);
            LexerCup lexerCup = new LexerCup(new StringReader(textoJava));
            Sintax s = new Sintax(lexerCup);
            try {
                s.parse();
                // ******LLENAMOS LOS DATOS DEL SINTAX A LAS TABLAS DE SIMBOLOS*********
                //mandamos las clases capturadas a la tabla de simbolos de clases
                for (int i = 0; i < s.getClases().size(); i++) {
                    tablaClases.agregarClase(s.getClases().get(i));
                }

                //mandamos los metodos capturados a la tabla de simbolos de metodos/funciones
                for (int i = 0; i < s.getFunciones().size(); i++) {
                    tablaMetodos.agregarMetodo(s.getFunciones().get(i));
                }

                //mandamos las variables capturadas a la tabla de simbolos de variables
                for (int i = 0; i < s.getVariables().size(); i++) {
                    tablaVariables.agregarVariable(s.getVariables().get(i));
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonExaminarCarpeta1;
    private javax.swing.JButton botonExaminarCarpeta2;
    private javax.swing.JButton botonReporteJson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathCarpeta1;
    private javax.swing.JTextField pathCarpeta2;
    private javax.swing.JTextArea reporteJSON;
    // End of variables declaration//GEN-END:variables
}
