
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 41;
  public static final int CHAR = 30;
  public static final int LLAVES_C = 6;
  public static final int LLAVES_A = 5;
  public static final int CASE = 35;
  public static final int DOUBLE = 31;
  public static final int DOS_PUNTOS = 7;
  public static final int PRIVATE = 24;
  public static final int CORCHETE_C = 11;
  public static final int INT = 27;
  public static final int CORCHETE_A = 10;
  public static final int FOR = 37;
  public static final int IDENTIFICADOR = 43;
  public static final int IGUAL = 12;
  public static final int IF = 32;
  public static final int DECIMAL = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int RETURN = 40;
  public static final int CLASE = 21;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int CADENA = 2;
  public static final int NEGACION = 19;
  public static final int MENOS = 14;
  public static final int MENOR = 17;
  public static final int BREAK = 36;
  public static final int VOID = 22;
  public static final int ERROR = 45;
  public static final int SWITCH = 34;
  public static final int MAYOR = 18;
  public static final int IMPORT = 20;
  public static final int ELSE = 33;
  public static final int PUNTO = 44;
  public static final int PROTECTED = 25;
  public static final int PARENTESIS_C = 4;
  public static final int WHILE = 38;
  public static final int FINAL = 26;
  public static final int PARENTESIS_A = 3;
  public static final int PUBLIC = 23;
  public static final int P_COMA = 8;
  public static final int STRING = 28;
  public static final int DIVISION = 15;
  public static final int DO = 39;
  public static final int MULTIPLICACION = 16;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVES_A",
  "LLAVES_C",
  "DOS_PUNTOS",
  "P_COMA",
  "COMA",
  "CORCHETE_A",
  "CORCHETE_C",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "MENOR",
  "MAYOR",
  "NEGACION",
  "IMPORT",
  "CLASE",
  "VOID",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "FINAL",
  "INT",
  "STRING",
  "BOOLEAN",
  "CHAR",
  "DOUBLE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "BREAK",
  "FOR",
  "WHILE",
  "DO",
  "RETURN",
  "NUMERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "PUNTO",
  "ERROR"
  };
}

