
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVES_C = 7;
  public static final int LLAVES_A = 6;
  public static final int PUNTO = 12;
  public static final int CADENA = 20;
  public static final int METODOS = 4;
  public static final int COMILLAS = 13;
  public static final int DOS_PUNTOS = 11;
  public static final int TIPO = 16;
  public static final int VARIABLES = 3;
  public static final int COMA = 10;
  public static final int NOMBRE = 5;
  public static final int EOF = 0;
  public static final int PARAMETROS = 18;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 14;
  public static final int CLASES = 2;
  public static final int P_COMA = 15;
  public static final int CORCHETE_C = 9;
  public static final int CORCHETE_A = 8;
  public static final int FUNCION = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASES",
  "VARIABLES",
  "METODOS",
  "NOMBRE",
  "LLAVES_A",
  "LLAVES_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO",
  "COMILLAS",
  "IDENTIFICADOR",
  "P_COMA",
  "TIPO",
  "NUMERO",
  "PARAMETROS",
  "FUNCION",
  "CADENA"
  };
}

